go.mod, go.sum
- Go.mod
- Go.sum
fix Go.sum checksum
```release-note
None
```
=> fix go.sum

README.md
fix #3 
README.md
update docs
```release-note
None
```
=> doc: update readme, add installation with go install

.github/workflows/cla.yml
fix #5 
.github/workflows/cla.yml
```release-note
None
```
=> ci: add cla assistant

.github/workflows/main_linux.yml, Makefile
fix #4 
support test coverage in ci
- Makefile
- .github/workflows/main_linux.yml
the CI  pipeline itself
```release-note
None
```
=> ci: support test coverage

README.md
fix #13 
README.md
```release-note
None
```
=> update readme: specify go install version

README.md
fix #14 
README.md
add badges in readme
```release-note
None
```
=> add godoc/license/coverage badges

.github/workflows/main_darwin.yml, .github/workflows/main_linux.yml, .github/workflows/main_windows.yml
.github/workflows/main_darwin.yml
.github/workflows/main_windows.yml
.github/workflows/main_linux.yml
```release-note
None
```
=> add pull_request to github workflow test triggers

pkg/swagger/generator/language.go, pkg/swagger/generator/language_test.go
related to #42 
pkg/swagger/generator/language.go
pkg/swagger/generator/language_test.go
update: reserve dash in attribute name, convert to underline
```release-note
1. reserve dash "-" from the attribute name and auto convert to "_" to avoid KCL syntax violation.
```
=> update: reserve dash in attribute name, convert to underline

.github/workflows/cla.yml
=> chore: bump cla kcl bot

pkg/swagger/generator/model.go, pkg/swagger/generator/structs.go, pkg/swagger/generator/templates/header.gotmpl
#44 
pkg/swagger/generator/model.go
pkg/swagger/generator/structs.go
pkg/swagger/generator/templates/header.gotmpl
resolve conflict import paths when there are different import paths with the same package name
1. first do the pre-process 
2. kcl-openapi generate model -f preprocessed-swagger.json
3. check the import stmts in `io/k8s/api/apps/v1/deployment_spec.k`
```release-note
resolve conflict import paths in the generated files
```
=> fix: resolve conflict import paths in the generated files

.github/workflows/main_linux.yml, pkg/kube_resource/generator/assets/files/api_spec/k8s/k8s.json, scripts/preprocess/Makefile, scripts/preprocess/main.py
fix #47 
scripts/preprocess/Makefile
scripts/preprocess/main.py
add pre-process script for k8s swagger.json file
```release-note
add pre-process script for k8s swagger.json file
```
=> add pre-process script for k8s swagger.json file

scripts/preprocess/main.py
scripts/preprocess/main.py
preprocess: fix to remove status from required list if set to omit
=> preprocess: fix to remove status from required list if set to omit

README.md, docs/generate_from_k8s_spec.md, scripts/preprocess/main.py
doc: kusion_kubernetes generation guide
=> doc: kusion_kubernetes generation guide

.github/workflows/release.yml, .goreleaser.yml
.github/workflows/release.yml
.goreleaser.yml
update repo name to kcl-lang in release ci
=> chore: update repo name to kcl-lang in release ci

README.md
update docs about #34 
readme.md
chore: update the install approaches in kcl-openapi quick-start guide
```release-note
None
```
=> chore: update the install approaches in kcl-openapi quick-start guide

.github/workflows/release.yml, .goreleaser.yml
chore: update docker namespace and password
=> chore: update docker namespace and password

.github/workflows/release.yml
fix: docker login username and password
=> fix: docker login username and password

.github/workflows/release.yml, .goreleaser.yml
fix: github token to upload artifact
=> fix: github token to upload artifact

examples/kube_resource/complex/muti_models/models/core_oam_dev_v1alpha2_containerized_workload.k, pkg/kube_resource/generator/testdata/muti_models/models/core_oam_dev_v1alpha2_containerized_workload.k, pkg/swagger/generator/templates/schemavalidator.gotmpl
fix #72 
fix: schema validator templates
+ pkg/swagger/generator/templates/schemavalidator.gotmpl
+ examples/kube_resource/complex/muti_models/models/core_oam_dev_v1alpha2_containerized_workload.k
=> fix: schema validator templates

pkg/kube_resource/generator/testdata/array_branch/models/operator_victoriametrics_com_v1beta1_vm_agent.k, pkg/swagger/generator/language.go, pkg/swagger/generator/model.go, pkg/swagger/generator/spec.go
fix #82 
fix https://github.com/kcl-lang/kcl/issues/1127
+ fix: crd default value
+ go.mod
+ pkg/swagger/generator/spec.go
+ pkg/swagger/generator/model.go
+ pkg/swagger/generator/language.go
+ pkg/kube_resource/generator/testdata/array_branch/models/operator_victoriametrics_com_v1beta1_vm_agent.k
+ pkg/kube_resource/generator/testdata/default_value/crossplane_io_compositions.yaml
=> fix: crd default value

.github/workflows/cla.yml
=> chore: update cla
